=== kbaird/Fate-XSLT/characters/Ravenloft/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, professions?, skills?, approaches?, languages?,
                     extras?, stunts, consequences?, hacks?, phase-trio?, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh base        CDATA #IMPLIED>
    <!ATTLIST refresh current     CDATA #IMPLIED>
    <!ATTLIST refresh free-stunts CDATA #IMPLIED>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type      CDATA #IMPLIED>
    <!ATTLIST aspect phase-num CDATA #IMPLIED>

  <!ELEMENT professions (profession*)>
    <!ELEMENT profession (#PCDATA)>
    <!ATTLIST profession name   CDATA #REQUIRED>
    <!ATTLIST profession rating CDATA #REQUIRED>

  <!ELEMENT skills (mode*, skill*)>
  <!ATTLIST skills name CDATA "Skills">
  <!ATTLIST skills shape (flat|pyramid) "pyramid">
    <!ELEMENT mode (skill*)>
    <!ATTLIST mode name   CDATA #REQUIRED>
    <!ATTLIST mode rating CDATA #REQUIRED>
    <!ELEMENT skill (#PCDATA)>
    <!ATTLIST skill name   CDATA #REQUIRED>
    <!ATTLIST skill rating CDATA #IMPLIED>
    <!ATTLIST skill add    CDATA #IMPLIED>

  <!ELEMENT approaches (approach*)>
    <!ELEMENT approach (#PCDATA)>
    <!ATTLIST approach name CDATA #REQUIRED>
    <!ATTLIST approach rating CDATA #REQUIRED>

  <!ELEMENT languages (#PCDATA)>

  <!ELEMENT extras (extra*, gadget*)>
    <!ELEMENT extra (#PCDATA)>
    <!ATTLIST extra cost CDATA #IMPLIED>
    <!ATTLIST extra name CDATA #IMPLIED>
    <!ELEMENT gadget (function+, flaws?, aspects?, benefits?)>
    <!-- benefits instead of stunts for ease of integration with ARRPG -->
    <!ATTLIST gadget name CDATA #REQUIRED>
    <!ATTLIST gadget notes CDATA #IMPLIED>
    <!ATTLIST gadget override-name CDATA #IMPLIED>
      <!ELEMENT function (#PCDATA)>
      <!ATTLIST function name CDATA #IMPLIED>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
          <!ATTLIST flaw name CDATA #IMPLIED>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

  <!ELEMENT stunts (stunt*)>
    <!ELEMENT stunt (#PCDATA)>
    <!ATTLIST stunt name CDATA #REQUIRED>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
    <!ATTLIST consequence effect CDATA #IMPLIED>
    <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

  <!ELEMENT hacks (#PCDATA)>
    <!ATTLIST hacks conditions          (true|false|wwn) "false"> <!-- Fate System Toolkit     -->
    <!ATTLIST hacks corruption          (true|false)     "false"> <!-- Fate Freeport Companion -->
    <!ATTLIST hacks credit-stress       (true|false)     "false"> <!-- Mostly for Mindjammer   -->
    <!ATTLIST hacks skill-modes         (true|false)     "false"> <!-- Fate System Toolkit     -->
    <!ATTLIST hacks single-stress-track (true|false)     "false">
    <!ATTLIST hacks stress-base-count   CDATA #IMPLIED>
    <!ATTLIST hacks systems-stress      (true|false)     "false"> <!-- Mostly for Mindjammer   -->
    <!ATTLIST hacks physical-consequence-skill CDATA #IMPLIED>    <!-- Consequences: skill granting an extra mild physical slot -->
    <!ATTLIST hacks mental-consequence-skill   CDATA #IMPLIED>    <!-- Consequences: skill granting an extra mild mental slot -->
    <!ATTLIST hacks physical-consequence-stunt CDATA #IMPLIED>    <!-- Consequences: stunt granting an extra mild physical slot -->

  <!ELEMENT phase-trio (phase*)>
    <!ELEMENT phase (events*)>
    <!ATTLIST phase num   CDATA #REQUIRED>
    <!ATTLIST phase title CDATA #IMPLIED>
      <!ELEMENT events (#PCDATA)>

  <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Ravenloft/darcy_williams.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Darcy Williams</charname>
    <playername>Jenn Cornish</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Burned-Out Former Roboticist</aspect>
    <aspect type="Trouble">I Don't Know What Will Happen If I Stop Flying</aspect>
    <aspect phase-num="1">Flying Is Complicated</aspect>
    <aspect phase-num="2">Science Is The Answer</aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Science"/>

    <skill rating="3" name="Athletics"/>
    <skill rating="3" name="Crafts"/>

    <skill rating="2" name="Deceive"/>
    <skill rating="2" name="Notice"/>
    <skill rating="2" name="Rapport"/>

    <skill rating="1" name="Physique"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
  </skills>
  <languages>
  </languages>
  <extras>
  </extras>
  <stunts>
    <stunt name="Up To Date With My Technical Journals">
      +2 to Create Advantages representing knowledge of the state-of-the-art and/or others' technology.
    </stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1">
      <events>
        In grad school, found that she could fly to relieve work-related stress,
        but immersing herself in work took her mind off being a monster.
      </events>
    </phase>
    <phase num="2">
      <events>
        Darcy built Nima's robot bodies and it sent her over the edge.
        She then quit robotics, hoping to balance her life.
      </events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/Ravenloft/alexa_sarandon.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Alexa Sarandon</charname>
    <playername>sample Weird World News character</playername>
    <description>&#160;</description>
  </id>
  <aspects>
    <aspect type="High-Concept">Fame-Obsessed Anchorwoman</aspect>
    <aspect type="Trouble">Must Find the Perfect Camera Angle</aspect>
    <aspect type="Motivation">I Will Make WWN The Top Channel!</aspect>
  </aspects>
  <skills name="Aptitudes" shape="flat">
    <skill rating="4" name="Bamboozle!"/>
    <skill rating="3" name="Entrap!"/>
    <skill rating="2" name="Investigate!"/>
    <skill rating="1" name="Run!"/>
  </skills>
  <stunts>
    <stunt name="Trapmaster">blah</stunt>
  </stunts>
  <hacks conditions="wwn" single-stress-track="true" stress-base-count="3"/>
</character>

=== kbaird/Fate-XSLT/characters/Ravenloft/djani.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>D'jani</charname>
    <playername>Brian Wilcox</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">I am a Plant Shaman</aspect>
    <aspect type="Trouble">Staying off the grid</aspect>
    <aspect phase-num="1">Plants are easier than humans</aspect>
    <aspect phase-num="2">Humans and their ramblings</aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Science (Botany)"/>

    <skill rating="3" name="Rapport"/>
    <skill rating="3" name="&#160;"/>

    <skill rating="2" name="&#160;"/>
    <skill rating="2" name="Notice"/>
    <skill rating="2" name="Will"/>

    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
  </skills>
  <languages>
  </languages>
  <extras>
  </extras>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1">
      <events>
        Relocated to the big city after (believing) I heard the plants there call to me
        for help (for the first time).
      </events>
    </phase>
    <phase num="2">
      <events>
        Knows Faulk from his frequent visits to the antique book section of Uruk's library,
        and is employed by Uruk as its chief gardener.
      </events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/Ravenloft/faulk_wintersson.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Faulk Wintersson</charname>
    <playername>Antonio McFadden</playername>
    <description>
      Male, 30, works for Nima at the Ijtihad library. Fighter (MMA).
      Fear, rage. "I call aqua bullshit", "Johnny Murderseed".
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Conflicted Vigilante working for humanity</aspect>
    <aspect type="Trouble">Don't want to cross the line</aspect>
    <aspect phase-num="1">Better to be rid of them, than become one</aspect>
    <aspect phase-num="2">Warrior Monk</aspect>
    <aspect>Knowledge is Power</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Fight"/>

    <skill rating="3" name="Lore"/>
    <skill rating="3" name="Notice"/>

    <skill rating="2" name="Athletics"/>
    <skill rating="2" name="Physique"/>
    <skill rating="2" name="Will"/>

    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
    <skill rating="1" name="&#160;"/>
  </skills>
  <languages>
  </languages>
  <extras>
  </extras>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <phase-trio>
    <phase num="1">
      <events>
        The world got worse with the rise of monsters. The fear and rancor caused become too much
        for me. Better to be rid of them, than become one. So I DID something about it.
      </events>
    </phase>
    <phase num="2">
      <events>
        Knows of Johnny from the library. Frequents antique book section for hours, and talks to
        himself. Cool with him and sense different emotions from him.
      </events>
    </phase>
  </phase-trio>
</character>
