=== kbaird/Fate-XSLT/characters/Do_FotFT/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, approaches, stunts, consequences?, notes?)>

  <!ELEMENT id (charname, playername, description)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh base        CDATA #IMPLIED>
    <!ATTLIST refresh current     CDATA #IMPLIED>
    <!ATTLIST refresh free-stunts CDATA #FIXED "2">

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>
    <!ATTLIST aspect type (Avatar|Banner-Trouble|Dragon|Free) "Free">

  <!ELEMENT approaches (approach*)>
    <!ELEMENT approach (#PCDATA)>
    <!ATTLIST approach name (Careful|Clever|Flashy|Forceful|Quick|Sneaky) #REQUIRED>
    <!ATTLIST approach rating CDATA #REQUIRED>

  <!ELEMENT stunts (stunt*)>
    <!ELEMENT stunt (#PCDATA)>
    <!ATTLIST stunt name CDATA #REQUIRED>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
    <!ATTLIST consequence effect CDATA #IMPLIED>
    <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

  <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Do_FotFT/curious_cat.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/do_fotft_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Curious Cat</charname>
    <playername>Morgan Baird</playername>
    <description>
      Red-haired girl, wearing clothing that looks like the coat of a leopard.
    </description>
  </id>
  <refresh free-stunts="2"/>
  <aspects>
    <aspect type="Avatar">Ooh... What's That?</aspect>
    <aspect type="Banner-Trouble">Easily Distracted</aspect>
    <aspect type="Dragon"></aspect>
    <aspect>I'll Find a Way In!</aspect>
    <aspect></aspect>
  </aspects>
  <approaches>
    <approach rating="2" name="Careful"/>
    <approach rating="3" name="Clever"/>
    <approach rating="0" name="Flashy"/>
    <approach rating="1" name="Forceful"/>
    <approach rating="1" name="Quick"/>
    <approach rating="2" name="Sneaky"/>
  </approaches>
  <stunts>
    <stunt name="Cheshire Catting">
      Because I am like the Cheshire Cat, I Sneakily Overcome at +2 when being invisible would help.
    </stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <notes>
    Wants to be good at escaping by being nimble &amp; cartwheeling in the air.
    Carries a spyglass.
    Comes from a cat-themed planet (Felinia?) where airships have cat decorations.
    They also have a festival called "Kitnip", and greet each other with high-fives.
  </notes>
</character>
