=== kbaird/Fate-XSLT/characters/Mindjammer/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh?, aspects, professions?, skills?, languages?,
                     extras?, stunts?, consequences?, hacks?, phase-trio?, notes?)>

  <!ELEMENT id (charname, playername, description, homeworld?)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT homeworld (#PCDATA)>
      <!ATTLIST homeworld name CDATA #REQUIRED>
      <!ATTLIST homeworld ref CDATA #IMPLIED>
      <!ATTLIST homeworld habituated-gravity CDATA #REQUIRED>
      <!ATTLIST homeworld tech-index CDATA #REQUIRED>

    <!ELEMENT refresh (#PCDATA)>
      <!ATTLIST refresh base        CDATA #IMPLIED>
      <!ATTLIST refresh current     CDATA #IMPLIED>
      <!ATTLIST refresh free-stunts CDATA #IMPLIED>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type      CDATA #IMPLIED>
      <!ATTLIST aspect phase-num CDATA #IMPLIED>

    <!ELEMENT professions (profession*)>
      <!ELEMENT profession (#PCDATA)>
      <!ATTLIST profession name   CDATA #REQUIRED>
      <!ATTLIST profession rating CDATA #REQUIRED>

    <!ELEMENT skills (mode*, skill*)>
    <!ATTLIST skills name CDATA "Skills">
    <!ATTLIST skills shape (flat|pyramid) "pyramid">
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #IMPLIED>
      <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT extras (extra*, gadget*)>
      <!ELEMENT extra (#PCDATA)>
        <!ATTLIST extra cost CDATA #IMPLIED>
        <!ATTLIST extra name CDATA #IMPLIED>
      <!ELEMENT gadget (function, flaws, aspects*, benefits*)>
      <!-- benefits instead of stunts for ease of integration with ARRPG -->
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ELEMENT function (#PCDATA)>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks conditions     (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks corruption     (true|false) "false"> <!-- Fate Freeport Companion -->
      <!ATTLIST hacks credit-stress  (true|false) "false"> <!-- Mostly for Mindjammer   -->
      <!ATTLIST hacks skill-modes    (true|false) "false"> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks stress-base-count CDATA #IMPLIED>
      <!ATTLIST hacks systems-stress (true|false) "false"> <!-- Mostly for Mindjammer   -->
      <!ATTLIST hacks physical-consequence-skill CDATA #IMPLIED>  <!-- Consequences: skill granting an extra mild physical slot -->
      <!ATTLIST hacks mental-consequence-skill   CDATA #IMPLIED>  <!-- Consequences: skill granting an extra mild mental slot -->
      <!ATTLIST hacks physical-consequence-stunt CDATA #IMPLIED>  <!-- Consequences: stunt granting an extra mild physical slot -->

    <!ELEMENT phase-trio (phase*)>
      <!ELEMENT phase (events*)>
        <!ATTLIST phase num   CDATA #REQUIRED>
        <!ATTLIST phase title CDATA #IMPLIED>
        <!ELEMENT events (#PCDATA)>

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Mindjammer/jenn_pc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname></charname>
    <playername>Jennifer Cornish</playername>
    <description>
      Arboe (Blue, pg 11)
      Met Junior at college on Kallistan
      homeworld's Chamber of Commerce paid for her Interplanetary Relations degree, went back home to work for them
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept"></aspect>
    <aspect type="Trouble"></aspect>
    <aspect phase-num="1"></aspect>
    <aspect phase-num="2"></aspect>
    <aspect phase-num="3"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Rapport"/>

    <skill rating="3" name="Bureaucracy"/>
    <skill rating="3" name="Intrusion"/>

    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>

    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio>
    <phase num="1">
      <events>
        Homeworld
        "We Take Care of Our Own"
        "Live and Let Live"
        "Aspiring to Join the Protectorate"
        "Don't Underestimate Us"
        "Redneck Justice"
      </events>
    </phase>
    <phase num="2">
      <events>&#160;</events>
    </phase>
    <phase num="3">
      <events>&#160;</events>
    </phase>
  </phase-trio>
</character>

=== kbaird/Fate-XSLT/characters/Mindjammer/junior.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Junior Dinkley</charname>
    <playername>Phil Bernard</playername>
    <description>
      Canid Genotype (MJ 40).
      CEO of a trading company that consists of just the PCs.
    </description>
    <homeworld name="Kallistan" ref="FH 8/67" habituated-gravity="0.9" tech-index="8"/>
  </id>
  <aspects>
    <aspect type="High-Concept">From Bastard Canid Throwaway to Secret CEO</aspect>
    <aspect type="Trouble"></aspect>
    <aspect phase-num="1"></aspect>
    <aspect phase-num="2"></aspect>
    <aspect phase-num="3"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Science"/>

    <skill rating="3" name="Resources"/>
    <skill rating="3" name="Technical"/>

    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>

    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="Scent Tracking">
      Your sense of smell is far superior to that of humans. You can track and
      recognise people by scent, and gain a +2 bonus on Investigate and Notice
      rolls related to smell. (FH pg 10)
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio>
    <phase num="1">
      <events>
        Rich canid, paid by family to stay away from home.
        The Dinkley family owns (among other things) a huge portion of Daedelus Corporation.
      </events>
    </phase>
    <phase num="2">
      <events>&#160;</events>
    </phase>
    <phase num="3">
      <events>&#160;</events>
    </phase>
  </phase-trio>
  <notes>
    Trouble: Enemies of the Family? (Or within the family?)
    Questions:
      Are you just an aimless drifter, or do you have some plan for your life?
  </notes>
</character>
