=== kbaird/Fate-XSLT/characters/AtomicRobo/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, current-fate-points, experience-points, aspects, skills,
                     languages?, stunts, consequences?, experiences?, notes?)>

  <!ELEMENT id (charname, playername, affiliation?, description?)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT affiliation (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT current-fate-points (#PCDATA)>
    <!ELEMENT experience-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (Concept|Mode|Ω)  #REQUIRED>
      <!ATTLIST aspect mode-name CDATA        #IMPLIED>
      <!ATTLIST aspect signature (true|false) "false">

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ATTLIST mode stress-type (mental|physical|split) #IMPLIED>
        <!ELEMENT skill (#PCDATA)>
        <!ATTLIST skill name   CDATA #REQUIRED>
        <!ATTLIST skill add    CDATA #IMPLIED>
        <!ATTLIST skill cost   CDATA #IMPLIED> <!-- For Weird calculations -->

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT stunts (stunt*, gadget*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt mega (true|false) "false">
      <!ATTLIST stunt name CDATA #REQUIRED>
      <!ELEMENT gadget (function+, flaws?, aspects?, benefits?)>
      <!ATTLIST gadget cost CDATA #IMPLIED>
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ATTLIST gadget notes CDATA #IMPLIED>
      <!ATTLIST gadget override-name CDATA #IMPLIED>
        <!ELEMENT function (#PCDATA)>
        <!ATTLIST function name CDATA #IMPLIED>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
          <!ATTLIST flaw name CDATA #IMPLIED>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

    <!ELEMENT experiences (experience*)>
      <!ATTLIST experiences suppress (true|false) "false">
      <!ELEMENT experience (#PCDATA)>
      <!ATTLIST experience used (true|false) "false">

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Romance_in_the_Air/2nd_foundation.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/romance_in_the_air_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Foundation (Second)</charname>
    <playername>Romance in the Air Great Power</playername>
    <description>An adaptation from Isaac Asimov's Foundation Series</description>
  </id>
  <refresh free-stunts="1"/>
  <aspects>
    <aspect type="High-Concept">Hidden Cabal of Mentalics and Psychohistorians</aspect>
    <aspect type="Color">We'll Change Your Mind Before You Know We've Gone</aspect>
    <aspect type="Internal&#160;Trouble">Squabbling at the table and Underestimating Others</aspect>
  </aspects>
  <skills shape="flat">
    <skill rating="4" name="Diplomacy"/>
    <skill rating="5" name="Espionage"/>
    <skill rating="2" name="Industry"/>
    <skill rating="3" name="Warfare"/>
  </skills>
  <stunts>
    <stunt name="The Seldon Plan Must Continue">
      By Degrading Espionage by 2 ranks, automatically Create the misleading Advantage
      "Utterly Destroyed" on the Second Foundation with 2 Free Invocations.
    </stunt>
    <stunt name="Janissaries">
      Because you command a secretive martial order of infiltrators,
      you can attack with Espionage to inflict military stress. When doing so,
      your Espionage degrades as if it were Warfare, and is restored the same
      way.
    </stunt>
  </stunts>
</character>

=== kbaird/Fate-XSLT/characters/TianxiaAccelerated/detective_dishi.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Detective Dishi</charname>
    <playername>Tianxia Accelerated</playername>
    <description>
      Lanky and vaguely awkward looking, Detective Dishi nevertheless might be the greatest force
      for justice in Băo Jiāng. A junior magistrate whose unwillingness to take bribes or look the
      other way when crimes are committed by the wealthy or powerful, this young man has already
      made a lot of enemies. He also has a few friends, a mix of soldiers, merchants, and local
      luminaries who help keep Dishi from catching a dagger in the back. Dishi favors nonlethal
      methods, but when called on to defend himself he wields his iron judge’s pen and reinforced
      fan with skill and enthusiasm.
    </description>
  </id>
  <refresh base="4"/>
  <aspects>
    <aspect type="High-Concept">One Good Cop in a Bad Town</aspect>
    <aspect type="Trouble">Problem With Authority</aspect>
    <aspect>Băo Jiāng's Greatest Detective</aspect>
    <aspect>Never Gives Up</aspect>
    <aspect>Unconventional Methods</aspect>
  </aspects>
  <skills name="Approaches" shape="flat">
    <skill rating="3" name="Careful"/>
    <skill rating="4" name="Clever"/>
    <skill rating="1" name="Flashy"/>
    <skill rating="0" name="Forceful"/>
    <skill rating="2" name="Quick"/>
    <skill rating="1" name="Sneaky"/>
  </skills>
  <extras>
    <gadget cost="2" name="Stone Crane 武術" notes="Careful, Clever">
      <benefits>
        <benefit name="Crane Hides in Reeds">
          Add a +2 bonus with using Full Defense to defend yourself. If defending others, gain
          2 Armor Rating against the attack instead.
        </benefit>
        <benefit name="Crane Stuns the Carp">
          If you succeed on a Careful of Clever physical attack with style, you may create a
          Stunned advantage on a target with a free invocation instead of taking a bonus.
        </benefit>
        <benefit name="Stone Resists the Blow">
          You gain 2 Armor against any physical attack you are aware of.
        </benefit>
        <!--
        <benefit name="江湖 (jiānghú) Rank 1: ☐">
          1 Free Invocation of Chi Armor per conflict.
          Automatically succeed on a Recover action for a Consequence if allowed to quietly meditate.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 2: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May grant Chi Armor or Consequence recovery to others.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 3: ☐">
          Another Free Invocation of Chi Armor per conflict.
          May recover a Moderate Consequence in half the time by reducing Chi Armor invocations per conflict back down to 1.
        </benefit>
        <benefit name="江湖 (jiānghú) Rank 4">
          May recover a Severe Consequence as above.
          Chi Armor now gives 3 Armor Rating instead of 2.
        </benefit>
        -->
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="Burden of Proof">
      Use Clever instead of Forceful to intimidate, frighten, or cower those you have
      incriminating evidence against.
    </stunt>
    <stunt name="Elementary!">
      +2 on Clever Overcome rolls based on investigation and detective work.
    </stunt>
    <stunt name="Just the Facts">
      Do not grant a free invoke to an opponent when failing to use Clever to Create an
      Advantage based on intuition or deception.
    </stunt>
  </stunts>
  <consequences/>
  <hacks single-stress-track="true" stress-base-count="3"/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicShadowrun/dwarf_decker.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Decker</charname>
    <playername>SR5 Quick-Start Rules</playername>
    <description>&#160;</description>
  </id>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Dwarf Decker</aspect>
    <aspect type="Mode" mode-name="Science"></aspect>
    <aspect type="Mode" mode-name="Intrigue"></aspect>
    <aspect type="Mode" mode-name="Action">Tough &amp; Decent with a Pistol</aspect>
    <aspect type="&#937;">Speaks Aztlaner Spanish (expand)</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Hacking"               add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <!--
         Specialize one trained skill. Hacking
         Focus one trained skill.
         Specialize one focused skill.
    -->
    <mode rating="2" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Stealth"   cost="2"/>
    </mode>
    <mode rating="1" name="Action" stress-type="split"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
  </skills>
  <stunts>
    <gadget name="Shiawase Cyber-5">
      <function>Cyberdeck</function>
      <flaws>
        <flaw>Illegal and not very concealable</flaw>
      </flaws>
    </gadget>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/tiffani.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Tiffani&#9829;</charname>
    <playername>Courtney Irving</playername>
    <affiliation>Tesladyne Oakland (Action Scientist PC)</affiliation>
    <description>&#160;</description>
  </id>
  <current-fate-points>4</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Terrifying Receptionist</aspect>
    <aspect type="Mode" mode-name="Action">Most Vicious Fighter on the West Coast</aspect>
    <aspect type="Mode" mode-name="Banter">Speaks Her Mind</aspect>
    <aspect type="Mode" mode-name="Intrigue">Sketchy Background, No Last Name</aspect>
    <aspect type="&#937;">You Wouldn't Like Me When I'm Hangry</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Action" stress-type="split"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="2" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1"/>
      <skill name="Will"     cost="1"/>
    </mode>
    <mode rating="1" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Stealth"   cost="2"/>
    </mode>
 </skills>
  <stunts>
    <stunt name="Look Into My Eye">
      Use Provoke to defend against threats and other fear-based attacks that deal mental harm.
    </stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
    Still has 1 Minor Milestone (ARRPG225) from stopping the hybrid queen.
    Regardless of what modes you have, if they're all standard modes you get ONE of the following improvements:
    * Specialize one trained skill.
    * Focus one trained skill and specialize one focused skill.
    * Focus three trained skills.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/nigel_gershmann.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>Nigel Gershmann</charname>
    <playername>NPC</playername>
    <description>
      Played by British historian Simon Schama. Wears a Baron Harkonnen-style anti-grav
      harness to get around in normal gravity and has obvious cranial implants.
    </description>
    <homeworld name="Astar planetoids" ref="FH 56" habituated-gravity="micro" tech-index="8"/>
  </id>
  <aspects>
    <aspect type="High-Concept">Highly-Educated Technocrat from the "Old Country"</aspect>
    <aspect type="Trouble">New Enough Arrival to Get Called "Carpetbagger"</aspect>
    <aspect type="Motivation">Expand Fathom's Recognition in the Far Havens</aspect>
    <aspect type="Instinct">Compromise Whenever Necessary On Anything But Land Rights</aspect>
    <aspect>Favors "Old Astar" Values over "New Canopy"</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Contacts"/>

    <skill rating="3" name="Knowledge"/>
    <skill rating="3" name="Resources"/>

    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Science"/>
    <skill rating="2" name="Technical"/>

    <skill rating="1" name="Empathy"/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <extras>
    <extra cost="3" name="HyperIntelligence">
      Gain a +2 bonus to any Knowledge, Science, or Technical roles where reasoning power is the determining factor.
      (Mindjammer pg 109)
    </extra>
  </extras>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio/>
  <notes>
    Jenn tells me his appearance and recent arrival from Astar is not especially noteworthy 
    in Canopy. He's just an outlier of a tendency already common to the populace. His age cohort
    probably chuckles behind his back that it took him long enough to emigrate from Astar.
    Shares the communitarian outlook common to Canopy and Astar, presumably inspired by the
    demands of Astar's fully artificial enviornment (like Traveller's Glisten).
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/nima_shirazi.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Nima Shirazi</charname>
    <playername>sample weird NPC</playername>
    <affiliation>&#160;</affiliation>
    <description>
      Originally an Iranian-American computer scientist and roboticist from Orange County, CA.
      After contracting a terminal illness, successfully transferred consciousness into a small
      (5ish) cadre of robotic insectoid bodies. Given the economics of micro-electronics
      manufacturing, he's now mostly Chinese.
    </description>
  </id>
  <current-fate-points>4</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Braintape in Multiple Insectoid Robots</aspect>
    <aspect type="Mode" mode-name="Science">Transhumanist Visionary</aspect>
    <aspect type="Mode" mode-name="Combat&#160;Stealthbot">Wall-Crawling Infiltrator</aspect>
    <aspect type="Mode" mode-name="Thief">Many Places at Once</aspect>
    <aspect type="Omega">&#160;</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Computer Science"     add="2"/>
      <skill name="Robotics"             add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <mode rating="2" name="Combat&#160;Stealthbot" stress-type="physical">
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Stealth"   cost="2"/>
      <skill name="Will"      cost="1"/>
    </mode>
    <mode rating="1" name="Thief" stress-type="physical"> <!-- ARRPG pg288 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Stealth"   cost="2"/>
      <!-- 4 pts of Improvements -->
    </mode>
  </skills>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
   1 pt of Improvements from Thief mode
   If one of your modes is Science, also apply ALL of the following improvements:
  X Specialize one trained skill.
  * Focus one trained skill.
  * Specialize one focused skill.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicShadowrun/gaichu.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Gaichu</charname>
    <playername>Kevin C. Baird</playername>
    <affiliation>Renraku (former), The Bolthole</affiliation>
    <description>From Shadowrun: Hong Kong</description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Ghoul Ex-Renraku Red Samurai</aspect>
    <aspect type="Mode" mode-name="Soldier">My Old Unit Betrayed Me</aspect>
    <aspect type="Mode" mode-name="Action"></aspect>
    <aspect type="Mode" mode-name="Beast">Inhuman Killing Machine</aspect>
    <aspect type="&#937;"></aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Soldier" stress-type="split"> <!-- ARRPG pg91 -->
     <skill name="Athletics" cost="2"/>
     <skill name="Combat"    cost="2" add="1"/>
     <skill name="Contacts"  cost="1"/>
     <skill name="Notice"    cost="1"/>
     <skill name="Physique"  cost="1" add="1"/>
     <skill name="Tactics"   cost="0" add="1"/>
     <skill name="Vehicles"  cost="2"/>
     <skill name="Will"      cost="1"/>
    </mode>
    <mode rating="2" name="Action" stress-type="split"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="1" name="Beast" stress-type="split"> <!-- ARRPG pg87 -->
     <skill name="Athletics"        cost="2"/>
     <skill name="Notice"           cost="1"/>
     <skill name="Physique"         cost="1"/>
     <skill name="Provoke"          cost="1"/>
     <skill name="Tooth &amp; Claw" cost="1"/> <!-- ARRPG pg87 -->
     <!-- Also Specialize 1 Trained Skill -->
     <!-- Combat & Tactics in Soldier Mode -->
    </mode>
  </skills>
  <stunts>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicShadowrun/eiger.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Eiger</charname>
    <playername>Kevin C. Baird</playername>
    <affiliation>Monika's Former Team</affiliation>
    <description>From Shadowrun: Dragonfall</description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">No-Nonsense Troll Ex-Soldier</aspect>
    <aspect type="Mode" mode-name="Soldier">I have training that the rest of you lack</aspect>
    <aspect type="Mode" mode-name="Action">I Hit Hard</aspect>
    <aspect type="Mode" mode-name="She-Devil">I Will Not Be Disrespected</aspect>
    <aspect type="&#937;">Sick Of This Flux-State Nonsense</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Soldier" stress-type="split"> <!-- ARRPG pg91 -->
     <skill name="Athletics" cost="2"/>
     <skill name="Combat"    cost="2"/>
     <skill name="Contacts"  cost="1"/>
     <skill name="Notice"    cost="1"/>
     <skill name="Physique"  cost="1" add="1"/>
     <skill name="Tactics"   cost="0"/>
     <skill name="Vehicles"  cost="2"/>
     <skill name="Will"      cost="1"/>
    </mode>
    <mode rating="2" name="Action" stress-type="split"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="1" name="She-Devil" stress-type="split"> <!-- ARRPG pg280 -->
     <skill name="Athletics" cost="2"/>
     <skill name="Combat"    cost="2"/>
     <skill name="Contacts"  cost="1"/>
     <skill name="Notice"    cost="1"/>
     <skill name="Vehicles"  cost="2"/>
     <skill name="Will"      cost="1"/>
    </mode>
    <!-- 1 pt of Improvements -->
    <!-- Physique in Soldier mode -->
  </skills>
  <stunts>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>
