=== kbaird/Fate-XSLT/characters/AtomicRobo/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, current-fate-points, experience-points, aspects, skills,
                     languages?, stunts, consequences?, experiences?, notes?)>

  <!ELEMENT id (charname, playername, affiliation?, description?)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT affiliation (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT current-fate-points (#PCDATA)>
    <!ELEMENT experience-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (Concept|Mode|Ω)  #REQUIRED>
      <!ATTLIST aspect mode-name CDATA        #IMPLIED>
      <!ATTLIST aspect signature (true|false) "false">

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ATTLIST mode stress-type (mental|physical|split) #IMPLIED>
        <!ELEMENT skill (#PCDATA)>
        <!ATTLIST skill name   CDATA #REQUIRED>
        <!ATTLIST skill add    CDATA #IMPLIED>
        <!ATTLIST skill cost   CDATA #IMPLIED> <!-- For Weird calculations -->

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT stunts (stunt*, gadget*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt mega (true|false) "false">
      <!ATTLIST stunt name CDATA #REQUIRED>
      <!ELEMENT gadget (function+, flaws?, aspects?, benefits?)>
      <!ATTLIST gadget cost CDATA #IMPLIED>
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ATTLIST gadget notes CDATA #IMPLIED>
      <!ATTLIST gadget override-name CDATA #IMPLIED>
        <!ELEMENT function (#PCDATA)>
        <!ATTLIST function name CDATA #IMPLIED>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
          <!ATTLIST flaw name CDATA #IMPLIED>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

    <!ELEMENT experiences (experience*)>
      <!ATTLIST experiences suppress (true|false) "false">
      <!ELEMENT experience (#PCDATA)>
      <!ATTLIST experience used (true|false) "false">

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/TesladyneOakland-NPCs/quetzalcoatl9.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Quetzalcoatl-9</charname>
    <playername>NPC</playername>
    <affiliation>Tenochca Timeline</affiliation>
    <description>
      A holographic projection of the perfect ideal of a Mesoamerican plumed serpent.
      Unsatisfied by their Gods' continued silence, the Tenochca took matters into their own hands.
    </description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Artifical Intelligence, Ready for Worshipping</aspect>
    <aspect type="Mode" mode-name="Banter">Trust is the Only Logical Choice</aspect>
    <aspect type="Mode" mode-name="Spirit">Divine Simulation</aspect>
    <aspect type="Mode" mode-name="Robot">I Will Become My Own Master</aspect>
    <aspect type="&#937;"></aspect>
  </aspects>
  <skills>
    <mode rating="4" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3" add="2"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1" add="2"/>
      <skill name="Will"     cost="1" add="2"/>
    </mode>
    <mode rating="3" name="Spirit" stress-type="mental"> <!-- ARRPG pg92 -->
      <skill name="Hover"   cost="2"/>
      <skill name="Provoke" cost="1"/>
      <!--
          Specialize 2 Trained Skills: Empathy, Rapport
          Focus      3 Trained Skills
      -->
    </mode>
    <mode rating="2" name="Robot" stress-type="physical"> <!-- ARRPG pg90 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <!--
          Specialize 1 Trained Skill: Will
          Focus      2 Trained Skills
      -->
    </mode>
  </skills>
  <stunts>
    <stunt mega="true" name="Incorporeal">
      You can move through solid objects with ease. Ignore physical obstacles. Under
      normal circumstances, you are also immune to all physical harm. It’s like the Bulletproof
      benefit, but much more all-encompassing. However, while in this state, you can’t interact
      with the physical world in any way. In addition, a combination of the proper equipment,
      the right conditions, and a precise command sequence on the hosting computer system
      (in other words, a compel on Divine Simulation) can force you
      into a corporeal state. This causes you to lose the benefits of this stunt and the use of the
      Hover skill until the end of the scene, at which time you revert to incorporeality again.
    </stunt>
    <stunt name="Fade Away">
      While incorporeal, you can choose to disappear—leave a scene—anytime. Spend a fate point to come back.
    </stunt>
    <!--
    <stunt name="Rocket Launchers &amp; Coughed Up Lugers">Weapon 2</stunt>
    <stunt mega="true" name="Wake of Destruction">
      When you succeed with style on a Tooth and Claw attack, spend a Fate Point to also inflict a Collateral
      Consequence (of the lowest available severity) in addition to any other stress or consequences the target has taken.
    </stunt>
    -->
  </stunts>
  <consequences/>
  <experiences suppress="true"/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland-NPCs/tizoc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>High Priest</charname>
    <playername>NPC</playername>
    <affiliation>Tenochca Timeline</affiliation>
    <description>
      Aztec-skinned champagne villian.
    </description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept"></aspect>
    <aspect type="Mode" mode-name=""></aspect>
    <aspect type="Mode" mode-name=""></aspect>
    <aspect type="Mode" mode-name=""></aspect>
    <aspect type="&#937;"></aspect>
  </aspects>
  <skills>
  </skills>
  <stunts>
    <!--
    <stunt name=""></stunt>
    -->
  </stunts>
  <consequences/>
  <experiences suppress="true"/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/harold_arrington.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Harold G. Arrington III</charname>
    <playername>Christopher Mitchell</playername>
    <affiliation>Branch Manager of Tesladyne Oakland</affiliation>
    <description>
      A young scientist that is striving to climb the proverbial ladder of success, which he
      envisions as defined through title.  As the new office manager, Harold is determined to
      manage by the book.  There are of course many books.... It's just about using the right
      one under the right circumstance.
    </description>
  </id>
  <current-fate-points>5</current-fate-points>
  <experience-points>2</experience-points>
  <aspects>
    <aspect type="Concept">Deep Blue with a Politician's Smile</aspect>
    <aspect type="Mode" mode-name="Banter">By the Book, Not Between the Lines</aspect>
    <aspect type="Mode" mode-name="Intrigue">Secrets are the Spice of Life</aspect>
    <aspect type="Mode" mode-name="Science">Rule Maker, Code Breaker</aspect>
    <aspect type="&#937;">It's Not About Success; It's About Legacy</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3" add="1"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1" add="2"/>
      <skill name="Will"     cost="1"/>
    </mode>
    <mode rating="2" name="Intrigue" stress-type="physical"> <!-- ARRPG pg84 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Burglary"  cost="1" add="1"/>
      <skill name="Contacts"  cost="1"/>
      <skill name="Deceive"   cost="2"/>
      <skill name="Notice"    cost="1" add="-1"/>
      <skill name="Stealth"   cost="2" add="2"/>
    </mode>
    <mode rating="1" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Computer Science"     add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(All Other Sciences)" cost="1"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Hiya!">
      Can Defend against physical attacks with Provoke
    </stunt>
    <stunt name="It Says Right Here in the Field Guide">
      +2 to Create an Advantage with Rapport on team members when quoting procedures
    </stunt>
    <stunt name="Pencilled-in">
      +2 to Create an Advantage with Burglary when using computers
    </stunt>
    <stunt name="Pencilled-in">
      Use Will to ignore the effects on physical stress box
    </stunt>
    <stunt name="Security System Manual">
      +2 to Create an Advantage with Computer Science when using security systems
    </stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
    <!--
      Minor Milestone from rescuing Dmitri: Burglary +1, Notice -1
      Minor Milestone from stopping the Hybrid Queen: Rapport +1, Empathy -1
    -->
    Still has 1 Minor Milestone (ARRPG225) from rescuing Dr. Chang from The Rock.
    Still has 1 Minor Milestone (ARRPG225) from breaking into Recombinatr.
    Still has 1 Minor Milestone (ARRPG225) from stopping Dr. Dinosaur.
      swap 2 Skills in the same Mode
      replace a Stunt
      rewrite a non-Concept Aspect
    Still has 1 Significant Milestone (ARRPG226) from stopping Dr. Dinosaur.
      1 point
      1 Experience Boost
    Still has 1 Severe Collateral Consequence (ARRPG227) from stopping Dr. Dinosaur.
      1 point
      can replace 1 Mode
      can rewrite any Aspect, including Concept
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/FateFreeport/gadi_melaku.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fate-freeport_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Gadi Melaku of the Ayhudi clan</charname>
    <playername>Kevin C. Baird</playername>
    <description>
      &nbsp;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Gold Dwarf Wizard from the Great Rift</aspect>
    <aspect type="Trouble">Must Prove Myself Worthy to my Prospective In-Laws</aspect>
    <aspect phase-num="1">Close to Zasheida's Family in Calimport</aspect>
    <aspect phase-num="2">M.M.S. from the Academy Arcane</aspect>
    <aspect phase-num="3">Border Patrol in the Steel Shields</aspect>
  </aspects>
  <skills shape="flat">
    <skill rating="1" name="Strength"/>
    <skill rating="2" name="Dexterity"/>
    <skill rating="2" name="Constitution"/>
    <skill rating="3" name="Intelligence"/>
    <skill rating="1" name="Wisdom"/>
    <skill rating="0" name="Charisma"/>
  </skills>
  <languages>
    Common, Draconic, Dwarvish, Elvish. Still trying to learn Halruaan.
  </languages>
  <extras>
    <gadget name="War Wizard">
      <function>
        2 Abjuration or Evocation spells. Uses Int for casting.
      </function>
      <benefits>
        <benefit cost="0" name="Arcane Shield">
          FFC pg33
        </benefit>
        <benefit cost="0" name="Magic Missile">
          FFC pg38
        </benefit>
      </benefits>
    </gadget>
    <gadget name="Manipulator">
      <function>
        3 Transmutation spells.
      </function>
      <benefits>
        <benefit cost="0" name="Alter Surface">
          FFC pg42
        </benefit>
        <benefit cost="0" name="Grace">
          FFC pg42
        </benefit>
        <benefit cost="0" name="Knock">
          FFC pg42
        </benefit>
      </benefits>
    </gadget>
    <gadget name="Seer">
      <function>
        3 divination spells.
      </function>
      <benefits>
        <benefit cost="0" name="Detect Magic">
          FFC pg35
        </benefit>
        <benefit cost="0" name="Fortune">
          FFC pg35
        </benefit>
        <benefit cost="0" name="Locate Object">
          FFC pg35
        </benefit>
      </benefits>
    </gadget>
  </extras>
  </stunts>
  <consequences/>
  <hacks corruption="true"/>
  <phase-trio>
    <phase num="1">
      <events>
        &nbsp;
      </events>
    </phase>
    <phase num="2">
      <events>
        &nbsp;
      </events>
    </phase>
    <phase num="3">
      <events>
        &nbsp;
      </events>
    </phase>
  </phase-trio>
  <notes>
    &nbsp;
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/john_simmons.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname nickname="Slim">John Simmons</charname>
    <playername>&#160;</playername>
    <affiliation>Tesladyne (Science Agent PC)</affiliation>
    <description>
      Slim spent most of World War II conducting test flights of America's most advanced airframes.
      Near the close of the war Slim was selected to fly Atomic Robo's unit deep behind German lines
      as the vanguard of Operation Paperclip. Slim would later become one of the original Science
      Agents of Tesladyne. His personal expertise in the cutting edge of aeronautics technology and
      the limits of the human body would serve the firm well in its early days.
    </description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Former Test Pilot</aspect>
    <aspect type="Mode" mode-name="Banter">&#160;</aspect>
    <aspect type="Mode" mode-name="Science">Fictional, Theoretical... Whatâ€™s the Difference?</aspect>
    <aspect type="Mode" mode-name="Action">&#160;</aspect>
    <aspect type="Omega">&#160;</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1"/>
      <skill name="Will"     cost="1" add="1"/>
    </mode>
    <mode rating="2" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Aeronautical Engineering" add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <mode rating="1" name="Action" stress-type="physical"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1"/>
      <skill name="Vehicles"  cost="2" add="1"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Test Pilot">
      +1 to overcome or create an advantage with Vehicles when flying an aircraft.
    </stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/carl_sagan.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Carl Sagan</charname>
    <playername>&#160;</playername>
    <affiliation>Cornell University, NASA</affiliation>
    <description>
Dr. Sagan's early work in astrophysics and the origins of life on Earth naturally led to
investigating the possibility of life on other planets...
Dr. Sagan contributed to many of NASA's robotic exploratory missions. He was perhaps best known
for his efforts to popularize scientific interests and pursuits through mass media.
    </description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">A Candle in the Dark</aspect>
    <aspect type="Mode" mode-name="Science">Extraordinary Claims Require Extraordinary Evidence</aspect>
    <aspect type="Mode" mode-name="Banter">America’s Foremost Science Communicator</aspect>
    <aspect type="Mode" mode-name="Celebrity">Turtleneck-Clad Cultural Icon</aspect>
    <aspect type="Omega">Know the Past to Understand the Present</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Astrophysics"         add="2"/>
      <skill name="Cosmology"            add="2"/>
      <skill name="Astronomy"            add="1"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1" add="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <mode rating="2" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1" add="1"/>
      <skill name="Deceive"  cost="2"/>
      <skill name="Empathy"  cost="3" add="1"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1" add="1"/>
      <skill name="Will"     cost="1"/>
    </mode>
    <mode rating="1" name="Celebrity"> <!-- ARRPG pg269 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Rapport"  cost="1"/>
      <!-- Improvement? -->
    </mode>
  </skills>
  <stunts>
    <stunt name="We Are Made Of Starstuff">
      You are a compelling speaker, and may use Cosmology to create an advantage in social situations if you can make it about science somehow.
    </stunt>
    <stunt name="People Are Not Stupid">
      +2 to overcome with Rapport when persuading someone in a way that respects their beliefs.
    </stunt>
    <stunt name="Confirmed Skeptic">
      Use Will to see through a lie with a logical or scientific basis.
    </stunt>
    <stunt name="Friends in High Places: ☐">
      Once per issue, when you have the time and opportunity to meet with your contacts in the
      scientific community, you can spend a fate point to acquire a cutting-edge or top-notch
      piece of technology. Once per volume, if done as part of creating an invention (page
      139), this can satisfy a serious catch.
    </stunt>
    <stunt name="A Few Minor Adjustments">
      Given almost enough time and serviceable tools, you can replace one (and only one) of a
      hardware's stunts or mega-stunts with another of your choosing.  If this adds more stunt
      benefits than it had before you messed with it, each additional one costs a fate point.
      The new stunt or mega-stunt lasts until the end of the issue, then vanishes.
    </stunt>
  </stunts>
  <consequences/>
  <experiences suppress="true"/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/survivor_robo.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname nickname="Survivor Robo">Dr. Atomic Robo Tesla</charname>
    <playername>NPC</playername>
    <affiliation>Tesladyne (retired)</affiliation>
    <description>
      The Robo from an alternate 2011 after the Cuban Missle Crisis in 1962 resulted
      in a global thermonuclear war that destroyed human civilization.
    </description>
  </id>
  <current-fate-points>5</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept" signature="true">Survivor Robo</aspect>
    <aspect type="Mode" mode-name="Survivor">I Failed Humanity When They Needed Me Most</aspect>
    <aspect type="Mode" mode-name="Science">Has-Been</aspect>
    <aspect type="Mode" mode-name="Robot">Virtually Indestructible</aspect>
    <aspect type="&#937;">&#160;</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Survivor" stress-type="split"> <!-- ARRPG pg256 -->
     <skill name="Athletics" cost="2"/>
     <skill name="Combat"    cost="2" add="1"/>
     <skill name="Notice"    cost="1"/>
     <skill name="Physique"  cost="1"/>
     <skill name="Vehicles"  cost="2"/>
     <skill name="Will"      cost="1"/>
     <!-- 5 pts of Improvements: Combat 2, Vehicles 2, Combat +1 -->
    </mode>
    <mode rating="2" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Electrical Engineering"       add="1"/>
      <skill name="Hyperdimensional Mathematics" add="2"/>
      <skill name="Nuclear Physics"              add="2"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <!--
         Specialize one trained skill. - HD Math
         Focus one trained skill.      - ElEng
         Specialize one focused skill. - Nuclear Physics
    -->
    <mode rating="1" name="Robot" stress-type="physical"> <!-- ARRPG pg90 -->
     <skill name="Athletics" cost="2"/>
     <skill name="Notice"    cost="1"/>
     <skill name="Physique"  cost="1"/>
     <!--
          Specialize 1 Trained Skill
          Focus      2 Trained Skills - Nuclear Physics
     -->
    </mode>
  </skills>
  <stunts>
    <stunt mega="true" name="Atomic Strength">
      Absolutely stronger than any human (Physique), but at a cost.
      Weapon: 2 with hand-to-hand attacks; +2 to Overcome with Athletics when jumping.
    </stunt>
    <stunt mega="true" name="Just Guns">
      Bulletproof, but weak to strong electromagnetism;
      Armor: 2 against everything else.
    </stunt>
    <stunt name="&#160;"> &#160; </stunt>
    <stunt name="&#160;"> &#160; </stunt>
  </stunts>
  <consequences/>
  <experiences suppress="true"/>
  <notes>
 </notes>
</character>

=== kbaird/Fate-XSLT/characters/TesladyneOakland/brian_wilcox_pc.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>&#160;</charname>
    <playername>Brian Wilcox</playername>
    <affiliation>Tesladyne Oakland (Action Scientist PC)</affiliation>
    <description>&#160;</description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">&#160;</aspect>
    <aspect type="Mode" mode-name="Science">&#160;</aspect>
    <aspect type="Mode" mode-name="Mode2">&#160;</aspect>
    <aspect type="Mode" mode-name="Mode3">&#160;</aspect>
    <aspect type="Omega">&#160;</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Gadgeteering?"        add="0"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
 </skills>
  <stunts>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
    <stunt name=" ">&#160;</stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes>
  Regardless of what modes you have, if they're all standard modes you get ONE of the following improvements:
  * Specialize one trained skill.
  * Focus one trained skill and specialize one focused skill.
  * Focus three trained skills.

  If one of your modes is Science, also apply ALL of the following improvements:
  * Specialize one trained skill.
  * Focus one trained skill.
  * Specialize one focused skill.

Modes with Athletics or Physique can give your character additional physical stress boxes, while modes with Provoke or Will can give
your character additional mental stress boxes. A mode with one or more of these skills rated at Fair (+2) adds one box, while one
rated at Good (+3) adds two boxes.

If a mode has skills that apply to both types, the bonus boxes can apply to either one. For example, the Action mode has Athletics,
Physique, and Provoke. If you've given it a rating of Good (+3), you could have two more physical stress boxes, two more mental stress
boxes, or one in each.

Bonus stress boxes from your Good (+3) and Fair (+2) modes are cumulative. So if you have Good (+3) Action and Fair (+2) Intrigue, both
of which have the Athletics skill, you can get three more physical stress boxesâ€”two from Action and one from Intrigue.
 </notes>
</character>
