=== kbaird/Fate-XSLT/characters/AtomicRobo/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, current-fate-points, experience-points, aspects, skills,
                     languages?, stunts, consequences?, experiences?, notes?)>

  <!ELEMENT id (charname, playername, affiliation?, description?)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT affiliation (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

    <!ELEMENT current-fate-points (#PCDATA)>
    <!ELEMENT experience-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (Concept|Mode|Ω)  #REQUIRED>
      <!ATTLIST aspect mode-name CDATA        #IMPLIED>
      <!ATTLIST aspect signature (true|false) "false">

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ATTLIST mode stress-type (mental|physical|split) #IMPLIED>
        <!ELEMENT skill (#PCDATA)>
        <!ATTLIST skill name   CDATA #REQUIRED>
        <!ATTLIST skill add    CDATA #IMPLIED>
        <!ATTLIST skill cost   CDATA #IMPLIED> <!-- For Weird calculations -->

    <!ELEMENT languages (#PCDATA)>

    <!ELEMENT stunts (stunt*, gadget*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt mega (true|false) "false">
      <!ATTLIST stunt name CDATA #REQUIRED>
      <!ELEMENT gadget (function+, flaws?, aspects?, benefits?)>
      <!ATTLIST gadget cost CDATA #IMPLIED>
      <!ATTLIST gadget name CDATA #REQUIRED>
      <!ATTLIST gadget notes CDATA #IMPLIED>
      <!ATTLIST gadget override-name CDATA #IMPLIED>
        <!ELEMENT function (#PCDATA)>
        <!ATTLIST function name CDATA #IMPLIED>
        <!ELEMENT flaws (flaw*)>
          <!ELEMENT flaw (#PCDATA)>
          <!ATTLIST flaw name CDATA #IMPLIED>
        <!ELEMENT benefits (benefit*)>
          <!ELEMENT benefit (#PCDATA)>
          <!ATTLIST benefit cost CDATA #IMPLIED>
          <!ATTLIST benefit name CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (Mild|Moderate|Severe) #REQUIRED>

    <!ELEMENT experiences (experience*)>
      <!ATTLIST experiences suppress (true|false) "false">
      <!ELEMENT experience (#PCDATA)>
      <!ATTLIST experience used (true|false) "false">

    <!ELEMENT notes (#PCDATA)>

=== kbaird/Fate-XSLT/characters/TianxiaAccelerated/po.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Po, the Dragon Warrior</charname>
    <playername>天下 Accelerated</playername>
    <description>
      Kind of sounds like Jack Black
    </description>
  </id>
  <refresh base="4"/>
  <aspects>
    <aspect type="High-Concept">The Dragon Warrior</aspect>
    <aspect type="Trouble">Complex Relationships with Father Figures</aspect>
    <aspect>Dreaming of Heroics Since Childhood</aspect>
    <aspect>Eager to Self-Improve</aspect>
    <aspect>Shīfu-Spotter</aspect>
  </aspects>
  <skills shape="flat">
    <skill rating="0" name="Careful"/>
    <skill rating="2" name="Clever"/>
    <skill rating="4" name="Flashy"/>
    <skill rating="3" name="Forceful"/>
    <skill rating="1" name="Quick"/>
    <skill rating="1" name="Sneaky"/>
  </skills>
  <extras>
    <gadget cost="2" name="Storm Dragon 武術" notes="Flashy, Forceful">
      <benefits>
        <benefit name="technique1">details</benefit>
        <benefit name="technique2">details</benefit>
      </benefits>
    </gadget>
  </extras>
  <stunts>
    <stunt name="stunt1">details</stunt>
  </stunts>
  <consequences/>
  <hacks single-stress-track="true" stress-base-count="4"/>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/sparrow2.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Sparrow II</charname>
    <playername>&#160;</playername>
    <affiliation>Section 13</affiliation>
    <description>
Daughter of Sparrow I, one of the few Sparrows to inherit the role while the
previous Sparrow was still able-bodied, and the first Sparrow to benefit from
the larger intelligence capability of Section 13. Sparrow II first encountered
Atomic Robo while attempting to thwart Dr. Vanadis Valkyrieâ€™s plot to begin
World War 3 in 1968. She retired to head of Section 13 in 1995.
    </description>
  </id>
  <current-fate-points>0</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept" signature="true">Britain's Top Agent</aspect>
    <aspect type="Mode" mode-name="Action">Mistress of the Martial Arts</aspect>
    <aspect type="Mode" mode-name="Science">A Keen and Inquisitive Mind</aspect>
    <aspect type="Mode" mode-name="Banter">Rapier-Sharp Wit</aspect>
    <aspect type="Omega">Underestimate Me At Your Peril</aspect>
  </aspects>
  <skills>
    <mode rating="3" name="Action" stress-type="physical"> <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat"    cost="2"/>
      <skill name="Notice"    cost="1"/>
      <skill name="Physique"  cost="1"/>
      <skill name="Provoke"   cost="1" add="2"/>
      <skill name="Vehicles"  cost="2"/>
    </mode>
    <mode rating="2" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
      <skill name="Chemistry"            add="1"/>
      <skill name="Notice"               cost="1"/>
      <skill name="Will"                 cost="1"/>
      <skill name="(all other Sciences)" cost="1"/>
    </mode>
    <mode rating="1" name="Banter" stress-type="mental"> <!-- ARRPG pg83 -->
      <skill name="Contacts" cost="1"/>
      <skill name="Deceive"  cost="2" add="1"/>
      <skill name="Empathy"  cost="3"/>
      <skill name="Provoke"  cost="1"/>
      <skill name="Rapport"  cost="1"/>
      <skill name="Will"     cost="1"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Judo Black Belt">
      When defending with Combat, on a success with style you may spend a fate point to deal a
      3-shift physical hit to the attacker (instead of getting a boost).
    </stunt>
    <stunt name="Sword Umbrella" mega="true">
      You often carry an umbrella that secretly serves as a sheath for a hidden and slender
      sword blade. It's the 60s; none of this is quite as ridiculous as it sounds. The sword
      has Weapon:2
    </stunt>
    <stunt name="Beauty And The Blade">
      +2 to attack or create an advantage with Combat when wielding a sword.
    </stunt>
    <stunt name="Wreckless Driver">
      Once per scene, when driving a car, you can reduce the harm dealt by an attack by up to 4
      shifts by letting the attacker have a situation aspect with one free invocation.
    </stunt>
  </stunts>
  <consequences/>
  <experiences>
    <experience/>
    <experience/>
    <experience/>
  </experiences>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/margrethe_jarlov.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>Margrethe Jarlov</charname>
    <playername>NPC</playername>
    <description>Played by comedienne Jen Kirkman</description>
    <homeworld name="Fathom" ref="FH 8" habituated-gravity="?" tech-index="7"/>
  </id>
  <aspects>
    <aspect type="High-Concept">Kirsten Gillibrand meets Beto O'Rourke</aspect>
    <aspect type="Trouble">Let Me Study That and Get Back to You</aspect>
    <aspect type="Motivation">Establish Myself as a Well-Connected Politician</aspect>
    <aspect type="Instinct">Don't Rock the Boat</aspect>
    <aspect></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Empathy"/>

    <skill rating="3" name="Contacts"/>
    <skill rating="3" name="Will"/>

    <skill rating="2" name="Knowledge"/>
    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Resources"/>

    <skill rating="1" name="Bureaucracy"/>
    <skill rating="1" name="Empathy"/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
    <stunt name="&#160;">&#160;</stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio/>
  <notes>
    The most generically "moderate" candidate for Far Havens Senator.

    Inspirational to some voters, but never in a policy-specific way. Broadly inoffensive, but also
    considered a bit of a lightweight. A "compromise" candidate in all senses of the term.
  </notes>
</character>

=== kbaird/Fate-XSLT/characters/AtomicRobo/kung_fu_trucker.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE character SYSTEM "../AtomicRobo/character.dtd">
<character>
  <id>
    <charname>Kung Fu Trucker</charname>
    <playername>NPC</playername>
    <affiliation>Deadly Disco Комиссар</affiliation>
    <description>
    &#160;
  </description>
  </id>
  <current-fate-points>4</current-fate-points>
  <experience-points>0</experience-points>
  <aspects>
    <aspect type="Concept">Kung Fu Trucker</aspect>
    <aspect type="Mode" mode-name="Martial&#160;Artist">Fists of Fury</aspect>
    <aspect type="Mode" mode-name="Trucker">Breaker, Break Her (Him, It)</aspect>
    <aspect type="Mode" mode-name="Action">Greased Lightning</aspect>
    <aspect type="Omega"/>
  </aspects>
  <skills>
    <mode rating="3" name="Martial&#160;Artist" stress-type="physical">
      <!-- ARRPG pg88 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Stealth" cost="2"/>
      <skill name="Will" cost="1"/>
    </mode>
    <mode rating="2" name="Trucker" stress-type="physical">
      <!-- Fighter Pilot, ARRPG pg296 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Vehicles" cost="2" add="1"/>
      <skill name="Will" cost="1"/>
    </mode>
    <mode rating="1" name="Action">
      <!-- ARRPG pg82 -->
      <skill name="Athletics" cost="2"/>
      <skill name="Combat" cost="2"/>
      <skill name="Notice" cost="1"/>
      <skill name="Physique" cost="1"/>
      <skill name="Provoke" cost="1"/>
      <skill name="Vehicles" cost="2"/>
    </mode>
  </skills>
  <stunts>
    <stunt name="Blind-Fight">Your ability to attack with Combat works unimpeded by conditions like darkness or other visual impairments.</stunt>
    <stunt name="Fist of Death">By concentrating your force into a powerful blow, you may devastate even the most potent of opponents. Once per opponent per fight, you may spend a fate point after landing a successful blow to cause your opponent to check their highest unchecked physical stress box (instead of taking stress equal to the shifts you succeeded by).</stunt>
    <stunt name="Leave My Friends Alone!">+2 to attack with Fight when your opponent’s most recent action was to attack one of your allies.</stunt>
    <stunt name="Riposte">If you succeed with style on a Combat defense, you can choose to inflict a 2-shift hit rather than take a boost.</stunt>
    <stunt name="Stunning Fist: ☐ ">Once per physical conflict, when you succeed on an unarmed attack, you may place the aspect Stunned on your opponent with one free invocation.</stunt>
  </stunts>
  <consequences/>
  <experiences suppress="true"/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/OutOfTheWoods/speaker_for_the_isolationists.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../Mindjammer/character.dtd">
<character>
  <id>
    <charname>"Speaker"</charname>
    <playername>NPC</playername>
    <description>Played by Dame Judi Dench</description>
    <homeworld name="Fathom" ref="FH 8" habituated-gravity="?" tech-index="7"/>
  </id>
  <aspects>
    <aspect type="High-Concept">Speaker for the Canopy Isolationists</aspect>
    <aspect type="Trouble">Xenophobes Ain't Xenoaware</aspect>
    <aspect type="Motivation">We Want Canopy to Deal with Outsiders for Us</aspect>
    <aspect type="Instinct">Let's Get This Conversation Over With</aspect>
    <aspect>I Assume You're Trying to Screw Us Over</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Bureaucracy"/>

    <skill rating="3" name="Provoke"/>
    <skill rating="3" name="Will"/>

    <skill rating="2" name="Deceive"/>
    <skill rating="2" name="Empathy"/>
    <skill rating="2" name="Resources"/>

    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <languages>
  </languages>
  <stunts>
    <stunt name="Esprit de Corps">
      Gain a +2 defend bonus when personnel are acting in solidarity to resist morale attacks or propaganda campaigns.
      (Mindjammer pg 274)
    </stunt>
    <stunt name="Secret Reserves ☐ ☐">
      Nobody knows what tricks the Isolationists have up their collective sleeves.
      Twice per session, can declare an Aspect with a free Invocation to represent that. (Tianxia: Spirits, Beasts, &amp; Spells, pg 48)
    </stunt>
    <stunt name="Stubborn">
      +2 to Attack with Bureaucracy when stonewalling / creating impediments to change.
    </stunt>
  </stunts>
  <consequences>
  </consequences>
  <hacks credit-stress="true"/>
  <phase-trio/>
  <notes/>
</character>

=== kbaird/Fate-XSLT/characters/SecretsOfCats/jexy.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Jexy</charname>
    <playername>Morgan Baird</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept"></aspect>
    <aspect type="Trouble"></aspect>
    <aspect type="Burdens"></aspect>
    <aspect type="True-Name"></aspect>
    <aspect type="Free"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name=""/>
    
    <skill rating="3" name=""/>
    <skill rating="3" name=""/>
    
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    <skill rating="2" name=""/>
    
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
    <skill rating="1" name=""/>
  </skills>
  <stunts>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    -->
  </consequences>
</character>

=== kbaird/Fate-XSLT/characters/SecretsOfCats/luna.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Luna</charname>
    <playername>Eva Doucette</playername>
    <description>
      &#160;
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Neighborhood Peacekeeper (Warden)</aspect>
    <aspect type="Trouble">Too Many Burdens</aspect>
    <aspect type="Burdens">Everyone On My Street</aspect>
    <aspect type="True-Name">Pragmatic Protector</aspect>
    <aspect type="Free"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Warding"/>
    
    <skill rating="3" name="Alchemy"/>
    <skill rating="3" name="Illusion"/>
    
    <skill rating="2" name="Empathy"/>
    <skill rating="2" name="Provoke"/>
    <skill rating="2" name="Will"/>
    
    <skill rating="1" name="Athletics"/>
    <skill rating="1" name="Fight"/>
    <skill rating="1" name="Investigate"/>
    <skill rating="1" name="Rapport"/>
  </skills>
  <stunts>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    -->
  </consequences>
</character>

=== kbaird/Fate-XSLT/characters/SecretsOfCats/gus.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/fcs_html.xsl"?>
<!DOCTYPE character SYSTEM "../FateCore/character.dtd">
<character>
  <id>
    <charname>Gus</charname>
    <playername>Gus</playername>
    <description>
      A cat who tries to get food and territory while transformed.
    </description>
  </id>
  <aspects>
    <aspect type="High-Concept">Burglar While Shaping Into Other Cats</aspect>
    <aspect type="Trouble">Territory</aspect>
    <aspect type="Burdens">Everyone</aspect>
    <aspect type="True-Name">Moonlit Hunter</aspect>
    <aspect type="Free"></aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Shaping"/>
    
    <skill rating="3" name="Burglary"/>
    <skill rating="3" name="Naming"/>
    
    <skill rating="2" name="Investigate"/>
    <skill rating="2" name="Notice"/>
    <skill rating="2" name="Stealth"/>
    
    <skill rating="1" name="Lore"/>
    <skill rating="1" name="Deceive"/>
    <skill rating="1" name="Will"/>
    <skill rating="1" name="Territory"/>
  </skills>
  <stunts>
    <stunt name="&#160;">
      +2 to use Shaping to transform into a non-cat.
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
    <stunt name="&#160;">
      &#160;
    </stunt>
  </stunts>
  <consequences>
    <!--
    <consequence severity="Mild">mild one</consequence>
    -->
  </consequences>
</character>
