=== kbaird/Fate-XSLT/characters/Diaspora/character.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, aspects, skills, stunts, consequences?, gear)>

  <!ELEMENT id (charname, playername, homeworld, cluster)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT homeworld (#PCDATA)>
    <!ELEMENT cluster (#PCDATA)>

  <!ELEMENT refresh (#PCDATA)>
    <!ATTLIST refresh base CDATA #IMPLIED>
    <!ATTLIST refresh current CDATA #IMPLIED>

  <!ELEMENT aspects (aspect*)>
    <!ELEMENT aspect (#PCDATA)>

  <!ELEMENT skills (skill*)>
    <!ELEMENT skill (#PCDATA)>
    <!ATTLIST skill name   CDATA #REQUIRED>
    <!ATTLIST skill rating CDATA #REQUIRED>

  <!ELEMENT stunts (stunt*)>
    <!ELEMENT stunt (#PCDATA)>
    <!ATTLIST stunt name CDATA #REQUIRED>

  <!ELEMENT stress (physical, mental)>
    <!ELEMENT physical (#PCDATA)>
    <!ELEMENT mental (#PCDATA)>

  <!ELEMENT consequences (consequence*)>
    <!ELEMENT consequence (#PCDATA)>
    <!ATTLIST consequence effect CDATA #IMPLIED>
    <!ATTLIST consequence severity (Mild|Moderate|Severe|Mild-Physical|Mild-Mental) #REQUIRED>

  <!ELEMENT gear (#PCDATA)>

=== kbaird/Fate-XSLT/characters/Diaspora/benny.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/diaspora_html.xsl"?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <id>
    <charname>Benny</charname>
    <playername>sample Diaspora character</playername>
    <homeworld>Old Copenhagen</homeworld>
    <cluster>TBD</cluster>
  </id>
  <refresh base="5"/>
  <aspects>
    <aspect>I hate the outdoors</aspect>
    <aspect>Natural mechanic</aspect>
    <aspect>Radiation Sickness</aspect>
    <aspect>Solution oriented</aspect>
    <aspect>Only part man</aspect>
    <aspect>Plug and play software</aspect>
    <aspect>Internal strife</aspect>
    <aspect>Sucks to be programmable</aspect>
    <aspect>Never going to have a master again</aspect>
    <aspect>Could always use another good program</aspect>
  </aspects>
  <skills>
    <skill rating="5" name="Repair"/>

    <skill rating="4" name="Bureaucracy"/>
    <skill rating="4" name="Intimidation"/>

    <skill rating="3" name="Tactics"/>
    <skill rating="3" name="Charm"/>
    <skill rating="3" name="Resolve"/>

    <skill rating="2" name="Oratory"/>
    <skill rating="2" name="Survival"/>
    <skill rating="2" name="Science"/>
    <skill rating="2" name="Vehicle"/>

    <skill rating="1" name="Agility"/>
    <skill rating="1" name="Profession: Farmer"/>
    <skill rating="1" name="Alertness"/>
    <skill rating="1" name="Profession: Teacher"/>
    <skill rating="1" name="Stamina"/>
  </skills>
  <stunts>
    <!--
         House ruling that Programmable costs double, so don't add another Stunt
         Cf. Diaspora pg 53
    -->
    <stunt name="Programmable">&#160;</stunt>
    <stunt name="Have a thing">&#160;</stunt>
  </stunts>
  <consequences>
    <consequence severity="Mild">mild one</consequence>
  </consequences>
  <gear>
    A little of this, a little of that
  </gear>
</character>
